### ISSUE TITLE
JellyForm blows up on custom string formats inside arrays

### ISSUE THREAD

**Issue by cyplo** [balena-io-modules/rendition#743]
Given:
```
version: 1
properties:
  - array:
      type: array
      items:
        type: dnsmasq-address
```
When clicking `add item` JellyForm emits an exception:
```
Error: No widget "dnsmasq-address" for type "string"
```

Link to playground [here](https://balena-io-playground.github.io/reconfix-play/index.html?yaml=dmVyc2lvbjogMQpwcm9wZXJ0aWVzOgogIC0gYXJyYXk6CiAgICAgIHR5cGU6IGFycmF5CiAgICAgIGl0ZW1zOgogICAgICAgIHR5cGU6IGRuc21hc3EtYWRkcmVzcw%3D%3D)
