### ISSUE TITLE
JellyForm: array item type is automatically switched (value based)

### ISSUE THREAD

**Issue by zrzka** [balena-io-modules/rendition#788]
**To Reproduce**

JellySchema:

```yaml
properties:
    - foo:
        type: array
        items:
            - type: integer
              title: Number
            - type: string
              title: Text
```

1. Open [Reconfix playground](https://balena-io-playground.github.io/reconfix-play/)
2. Use the provided JellySchema
3. Click on the _+ Add item_
4. Change added item type to `Number`
5. Type `a`
6. Item type is switched to `Text`

**Expected behavior**

Here I'm not 100% sure, but it surprised me. I'd expect that the type will remain set to `Number` and that the validator will tell me that it's not a valid `type: integer`.

I'm happy to discuss how it should behave.

Even more contrived example:

```yaml
properties:
    - foo:
        type: array
        items:
            - type: integer
              title: Integer
            - type: number
              title: Number
```

And try:

* Switch item type to `Number`
* Start typing `10.0`
  * When you type `1`, it's switched to `Integer`
  * When you type `.`, it's switched back to the `Number`

It just feels weird, I may be wrong.

**Specifications (please complete the following information):**

* Browser
  * Safari - https://whatsmybrowser.org/b/QCH3X6V  
  * Firefox - https://whatsmybrowser.org/b/V3T24HV
* OS: macOS 10.14.3 (18D109)
