### ISSUE TITLE
JellyForm: textfield focus is lost when the array item type is changed

### ISSUE THREAD

**Issue by zrzka** [balena-io-modules/rendition#789]
**To Reproduce**

JellySchema:

```yaml
properties:
    - foo:
        type: array
        items:
            - type: integer
              title: Integer
            - type: number
              title: Number
```

1. Open [Reconfix playground](https://balena-io-playground.github.io/reconfix-play/)
2. Use the provided JellySchema
3. Click on the _+ Add item_
4. Change added item type to `Number`
5. Type `10`

* Item type is switched to `Integer`
* Textfield contains just `1`

Focus is probably lost and `0` ends in the void.

**Screenshots**

![focus-gone](https://user-images.githubusercontent.com/1084172/54759773-0e423e00-4bef-11e9-8a9b-f1585bf9e631.gif)

**Expected behavior**

Let me type `10`. It's somehow also related to #788.

**Specifications (please complete the following information):**

* Browser
  * Firefox - https://whatsmybrowser.org/b/V3T24HV
* OS: macOS 10.14.3 (18D109)

(It works in Safari, only Firefox is broken)
